### ISSUE TITLE
Meta discussion on structure and standards

### ISSUE THREAD

**Issue by HikariNeee** [allthingslinux/tux#193]
Instead of focusing on newer features, we should focus on rewriting the core constructs like the error handler and give the help command a makeover for once as well as provide stable APIs for stuff like buttons.

This list is a TODO for all that is to be done.

- [x] Create a generic button handler class
- [x] Add docstrings
- [x] Document commands
- [x] Create a generic pagination class
- [x] Create a generic error handler that prettifies most of the output
- [x] Redesign the help command

**Comment by kzndotsh** [comment]
I agree with this, sounds good to me. I will hold off on any new fancy features and focus on cleaning up what is current.

**Comment by electron271** [comment]
agreed

**Comment by kzndotsh** [comment]
6 hours later... everything? or almost everything has been fully doc-stringed.

**Comment by Quelln** [comment]
I'll push the update to my run command along with the updated docstrings in a few hours when it finishes, any idea how many commands are left?

**Comment by electron271** [comment]
we also desperately need to stop hard coding stuff and make stuff work across multiple servers
