### ISSUE TITLE
Official v1 release plans

### ISSUE THREAD

**Issue by kzndotsh** [allthingslinux/tux#247]
Let us discuss what is required for our first "official" v1 release.

It's important we get to an official starting release so that we can start a proper workflow/release cycle moving forward and not fall into a never ending roadmap of feature creep.

- [ ] What will our official change log/roadmap consist of?
- [ ] What will be required infrastructure/CI CD/systems wise?
- [ ] What will be required branding wise?
- [ ] What will be required code standard wise?
- [ ] What will be required database wise?
- [ ] What will be our main offering list/commands/etc so to speak?

Etcetera, etcetera. All ideas and considerations are welcome.

**Comment by kzndotsh** [comment]
Proposed command groups/commands list

Admin
- .

Moderation
- .

Utility
- .

Fun
- .

**Comment by kzndotsh** [comment]
Key features/integrations/services
- .

**Comment by electron271** [comment]
i dont think we really need anything or much branding wise that i can think of

**Comment by kzndotsh** [comment]
> i dont think we really need anything or much branding wise that i can think of

 Maybe a proper final run through reading README and other docs if that counts as branding lol.

**Comment by HikariNeee** [comment]
IMO, getting a nice looking help command should be the first priority.

And two, a generic error handler for any command (which we still don't have iirc)

**Comment by electron271** [comment]
we need hybrid commands as the first priority imo

**Comment by HikariNeee** [comment]
To be honest, prefix commands are good enough
It only becomes a problem when you get added in too many servers.

**Comment by electron271** [comment]
decided in #525 
if this is incorrect feel free to reopen
